### ISSUE TITLE
VS2015 version 14 compile error

### ISSUE THREAD

**Issue by chengstone** [BNiels/NFS#4]
Hi,
i'm using visual studio 2015 version 14 to complie the code，got 8 errors

error messages :

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2244	'lag::TypeStruct<Front,Back...>::size': unable to match function definition to an existing declaration	NFS	c:\users\cheng.sd\downloads\nfs-master\nfs\api\lm4000_typelist\typestruct.h	162	

Error	C2244	'lag::TypeStruct<Front,Back...>::size': unable to match function definition to an existing declaration	NFS	c:\users\cheng.sd\downloads\nfs-master\nfs\api\lm4000_typelist\typestruct.h	162	

Error	C2244	'lag::TypeStruct<Front,Back...>::size': unable to match function definition to an existing declaration	NFSU	c:\users\cheng.sd\downloads\nfs-master\nfs\api\lm4000_typelist\typestruct.h	162	

Error	C2244	'lag::TypeStruct<Front,Back...>::size': unable to match function definition to an existing declaration	NFSU	c:\users\cheng.sd\downloads\nfs-master\nfs\api\lm4000_typelist\typestruct.h	162	

Error	C2244	'lag::TypeStruct<Front,Back...>::size': unable to match function definition to an existing declaration	NFSU	c:\users\cheng.sd\downloads\nfs-master\nfs\api\lm4000_typelist\typestruct.h	162	

Error	C2244	'lag::TypeStruct<Front,Back...>::size': unable to match function definition to an existing declaration	NFSU	c:\users\cheng.sd\downloads\nfs-master\nfs\api\lm4000_typelist\typestruct.h	162	

Error	C2244	'lag::TypeStruct<Front,Back...>::size': unable to match function definition to an existing declaration	NFSU	c:\users\cheng.sd\downloads\nfs-master\nfs\api\lm4000_typelist\typestruct.h	162	

Error	C2244	'lag::TypeStruct<Front,Back...>::size': unable to match function definition to an existing declaration	NFSU	c:\users\cheng.sd\downloads\nfs-master\nfs\api\lm4000_typelist\typestruct.h	162

## But, when i comment out below code in the file ‘TypeStruct.h’ line 158~162， then solve the issue：
    template<typename Front, typename ...Back>
	inline constexpr unsigned int TypeStruct<Front, Back...>::size()
	{
		return SizeTypes<Front, Back...>;
	}

its strange

**Comment by Nielsbishere** [comment]
Right now, I'm redoing a big part of NFS. I've found that the current system doesn't compile on every compiler (on msvc it only builds without optimizations (Debug)) and the code base is one big mess.

**Comment by chengstone** [comment]
great, awesome

**Comment by Nielsbishere** [comment]
Does the compile work for the branch "NFS reloaded"? It uses CMake and a new system instead of Visual Studio. This branch has a few new features, but it is also not fully completed yet, I think by tomorrow or the day after, it will be close.

**Comment by Nielsbishere** [comment]
AFAIK, the NFS-Reloaded branch works with 2015 and 2017, though NFSU doesn't work with x86 yet. I'm fixing some template issues that should also allow g++ to work.

**Comment by chengstone** [comment]
thanks your great work, i'll try NFS-Reloaded
